# Generated by Django 5.2.4 on 2025-07-28 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("group", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlobModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Unnamed Blob", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("tz", models.CharField(default="UTC", max_length=100)),
                ("default_start", models.CharField(default=40)),
                ("default_end", models.CharField(default=40)),
                ("schedulable_start", models.CharField(default=40)),
                ("schedulable_end", models.CharField(default=40)),
                ("is_splittable", models.BooleanField(default=False)),
                ("is_overlappable", models.BooleanField(default=False)),
                ("is_invisible", models.BooleanField(default=False)),
                ("max_splits", models.IntegerField(default=0)),
                ("min_split_duration", models.DurationField(default=0)),
                ("dependencies", models.JSONField(default=list)),
                (
                    "tags",
                    models.ManyToManyField(blank=True, to="elastic_scheduler.tagmodel"),
                ),
            ],
        ),
    ]
