# Generated by Django 5.2.4 on 2025-07-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elastic_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blobmodel",
            name="default_end",
            field=models.DateTimeField(default=40),
        ),
        migrations.AlterField(
            model_name="blobmodel",
            name="default_start",
            field=models.DateTimeField(default=40),
        ),
        migrations.AlterField(
            model_name="blobmodel",
            name="schedulable_end",
            field=models.DateTimeField(default=40),
        ),
        migrations.AlterField(
            model_name="blobmodel",
            name="schedulable_start",
            field=models.DateTimeField(default=40),
        ),
    ]
