# Generated by Django 5.2.4 on 2025-07-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elastic_scheduler", "0002_alter_blobmodel_default_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blobmodel",
            name="default_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="blobmodel",
            name="default_start",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="blobmodel",
            name="schedulable_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="blobmodel",
            name="schedulable_start",
            field=models.DateTimeField(),
        ),
    ]
