# Generated by Django 5.2.4 on 2025-08-01 23:31

import tzlocal.unix
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elastic_scheduler", "0003_alter_blobmodel_default_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blobmodel",
            name="tz",
            field=models.CharField(
                default=tzlocal.unix.get_localzone_name, max_length=100
            ),
        ),
    ]
