# Generated by Django 5.2.4 on 2025-08-01 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elastic_scheduler", "0004_alter_blobmodel_tz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagmodel",
            name="group",
        ),
    ]
